### ISSUE TITLE
Setting Milestones

### ISSUE THREAD

**Issue by valerius21** [elegal-ev/Keres#21]
We still got none of them.

**Comment by lquenti** [comment]
First working Version

**Comment by lquenti** [comment]
Working version for the programming course (where they can fix it)

**Comment by lquenti** [comment]
Release on Mavencentral or sth alike

**Comment by lquenti** [comment]
Further Templating using an external library (which I'd love to write myself with you)

**Comment by lquenti** [comment]
We should also add that to the readme
